const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const START_PORT = Number(process.env.PORT || 4173);
const DIST = path.join(__dirname, 'dist');
const characters = [
  { name: 'Rocky the Dragon', type: 'A brave little dragon with a big imagination.', speech: 'Hi! I’m Rocky the Dragon!' },
  { name: 'Bloop the Space Cat', type: 'A curious explorer who collects moon rocks.', speech: 'Hello, Earth friend! Want to explore the stars?' },
  { name: 'Zippy the Super Car', type: 'A speedy helper who never leaves a friend behind.', speech: 'Vroom! I’m Zippy. Where should we zoom today?' }
];

function json(response, status, payload) { const body = JSON.stringify(payload); response.writeHead(status, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' }); response.end(body); }
function readBody(request) { return new Promise((resolve, reject) => { let data = ''; request.on('data', chunk => { data += chunk; if (data.length > 200000) request.destroy(); }); request.on('end', () => { try { resolve(data ? JSON.parse(data) : {}); } catch (error) { reject(error); } }); request.on('error', reject); }); }
function chooseCharacter(fileName = '', source = 'upload') { const lower = fileName.toLowerCase(); if (lower.includes('cat')) return characters[1]; if (lower.includes('car')) return characters[2]; if (source === 'camera') return characters[crypto.randomInt(2)]; return characters[crypto.randomInt(characters.length)]; }
function storyFor(character) { return [`${character.name} discovered a tiny star tucked inside the drawing.`, `“It only shines when someone is brave enough to imagine,” ${character.name.split(' the ')[0]} whispered. Together, you carried it home.`]; }
function replyFor(message, character, language = 'en-US') { const text = String(message || '').toLowerCase(); if (language.startsWith('si')) { if (text.includes('name')) return `මගේ නම ${character.name}. මම ඔබගේ චිත්‍රයෙන් ජීවමාන වුණා!`; return 'ඒක හරිම ලස්සන අදහසක්! අපි එකට වික්‍රමයකට යමු.'; } if (language.startsWith('ta')) { if (text.includes('name')) return `என் பெயர் ${character.name}. உங்கள் ஓவியத்திலிருந்து நான் உயிர் பெற்றேன்!`; return 'அது ஒரு அற்புதமான யோசனை! நாம் ஒன்றாக ஒரு சாகசத்திற்கு செல்வோம்.'; } if (text.includes('name')) return `My name is ${character.name}. I was born from your drawing!`; if (text.includes('story') || text.includes('adventure')) return 'My best adventure is the one we imagine together. Let’s begin!'; if (text.includes('hello') || text.includes('hi')) return 'Hello, friend! I’m happy you brought me to life.'; return `That is a wonderful idea! ${character.name} thinks we should explore it together.`; }
async function api(request, response, route) { try { const input = await readBody(request); if (route === '/api/scan') { const base = chooseCharacter(input.fileName, input.source); return json(response, 200, { ok: true, mode: 'mock', source: input.source || 'upload', character: { ...base, id: crypto.randomUUID(), createdAt: new Date().toISOString() } }); } if (route === '/api/story') return json(response, 200, { ok: true, mode: 'mock', story: storyFor(input.character || characters[0]) }); if (route === '/api/chat') return json(response, 200, { ok: true, mode: 'mock', reply: replyFor(input.message, input.character || characters[0], input.language) }); return json(response, 404, { ok: false, error: 'Unknown API route' }); } catch (error) { return json(response, 400, { ok: false, error: 'Invalid request' }); } }
function serveStatic(request, response) { const requested = request.url === '/' ? '/index.html' : request.url; const safePath = path.normalize(requested).replace(/^([.][.][/\\])+/, ''); const filePath = path.join(DIST, safePath); if (!filePath.startsWith(DIST) || !fs.existsSync(filePath) || fs.statSync(filePath).isDirectory()) return json(response, 404, { error: 'Not found' }); const ext = path.extname(filePath); const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.svg': 'image/svg+xml' }; response.writeHead(200, { 'Content-Type': types[ext] || 'application/octet-stream' }); fs.createReadStream(filePath).pipe(response); }
const server = http.createServer((request, response) => { const url = new URL(request.url, `http://${request.headers.host || 'localhost'}`); if (url.pathname === '/api/health') return json(response, 200, { ok: true, service: 'draw-to-life-api', mode: 'mock' }); if (url.pathname.startsWith('/api/')) return api(request, response, url.pathname); return serveStatic(request, response); });
function listen(port) { server.once('error', error => { if (error.code === 'EADDRINUSE') { console.log(`Port ${port} is busy. Trying port ${port + 1}…`); listen(port + 1); } else { throw error; } }); server.listen(port, () => console.log(`Draw-to-Life World running at http://localhost:${port}`)); }
listen(START_PORT);
